//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHSystem.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientMedicationList
    {
        public int Id { get; set; }
        public int PatientID { get; set; }
        public string MedicationName { get; set; }
        public string Dosage { get; set; }
        public string Direction { get; set; }
        public string OrderedBy { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string DurationType { get; set; }
        public string Note { get; set; }
    
        public virtual tblPatient tblPatient { get; set; }
    }
}
