//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHSystem.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPatient()
        {
            this.tblPatientMedicationLists = new HashSet<tblPatientMedicationList>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Active { get; set; }
        public int FacilityID { get; set; }
        public string DateCreated { get; set; }
        public string DateUpdated { get; set; }
    
        public virtual tblFacility tblFacility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPatientMedicationList> tblPatientMedicationLists { get; set; }
    }
}
